name: SimplePlugin
version: 1.0
main: org.example.SimplePlugin
commands:
  ping:
    description: "This command displays the ping."
    usage: "/sp <command>"
  pings:
    description: "This command displays the pings of all players"
    usage: "/sp <command>"
  go:
    description: "Goto the place you set"
    usage: "/sp go <name>"
  set:
    description: "Set a place to go"
    usage: "/sp set <name>"
  check:
    description: "check all points of tp"
    usage: "/sp <command>"
  delete:
    description: "delete a tp point"
    usage: "/sp set <name>"