name: SimplePlugin
version: 1.0
main: org.example.SimplePlugin
commands:
  ping:
    description: "This command displays the ping."
    usage: "/<command>"
  pings:
    description: "This command displays the pings of all players"
    usage: "/<command>"
  go:
    description: "Goto the place you set"
    usage: "/go <name>"
  set:
    description: "Set a place to go"
    usage: "/set <name>"
  check:
    description: "check all points of tp"
    usage: "/<command>"
  delete:
    description: "delete a tp point"
    usage: "/set <name>"
  spawn:
    description: "goto spawn"
    usage: "/<command>"
  setspawn:
    description: "setting a spawn place"
    usage: "/<command>"
  biomes:
    description: "get biome for the player postion"
    usage: "/<command>"